In [2]:
import numpy as np
mylist  = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [2]:
nested_list=[[1,2],[3,4],[5,6]]
nested_list

[[1, 2], [3, 4], [5, 6]]

In [3]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(0,10,2)
#start,stop,commmmon_difference

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((4,10))
#Rows,Columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
np.linspace(0,10,5)
#linear_space
#start,stop,nnumber_of_elemments

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
np.eye(5)
#Identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.random.rand(2)
#2 random Numbers between 0 and 1
np.random.rand(3,4)
#random Numbers between 0 and 1 in a 3x4 mtrix

array([[0.66930151, 0.90140326, 0.13561918, 0.19040493],
       [0.20848491, 0.8530544 , 0.60243831, 0.62576467],
       [0.24642236, 0.01129344, 0.80725277, 0.75397872]])

In [12]:
np.random.randint(1,100,(2,3))

array([[48, 68, 21],
       [56, 25, 74]])

In [13]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])