In [2]:
import numpy as np
mylist  = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [3]:
nested_list=[[1,2],[3,4],[5,6]]
nested_list

[[1, 2], [3, 4], [5, 6]]

In [4]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
np.arange(0,10,2)
#start,stop,commmmon_difference

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((4,10))
#Rows,Columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.linspace(0,10,5)
#linear_space
#start,stop,nnumber_of_elemments

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.eye(5)
#Identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.rand(2)
#2 random Numbers between 0 and 1
np.random.rand(3,4)
#random Numbers between 0 and 1 in a 3x4 mtrix

array([[0.27924632, 0.3935528 , 0.65805385, 0.65230063],
       [0.89544092, 0.23764605, 0.01320595, 0.10354014],
       [0.82151934, 0.59521896, 0.02767945, 0.90560242]])

In [10]:
np.random.randint(1,100,(2,3))

array([[95, 55, 61],
       [22, 22, 74]])

In [11]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

Numpy Index Selection

In [12]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Broadcasting values
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Copying of array is not as same as slicing. 
so we have to explicitly declare a copy using .copy() function

In [15]:
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])